name: 功能建议和新功能开发请求
description: 功能建议和新功能开发请求
title: 用一句话描述这个问题
labels: ["feature", "triage"]
body:
  - type: textarea
    id: what-you-want
    attributes:
      label: 功能建议
      placeholder: |
        请在这里描述你对现有功能的建议或者希望添加的新功能。
        如果你对功能的实现方案已经有初步设想，也欢迎一并说明。
    validations:
      required: true
  - type: checkboxes
    id: promise
    attributes:
      label: 提交须知
      description: 提交问题前，请确认你使用的是[最新版本](https://github.com/Yuukiy/JavSP/releases/latest)并且已经阅读过[Wiki帮助文档](https://github.com/Yuukiy/JavSP/wiki)
      options:
        - label: 我确认使用的是最新版本并且已经阅读过Wiki帮助文档
          required: true
